Repository openlawteam/tribute-contracts, pull requests merged in 2021-09, with the labels that each got.

#371 fix: code coverage
  .gitignore
  .solcover.js
  package.json
  scripts/coverage.js
  truffle-config.js
Labels: chore

#370 feat: Onboarding members with ERC1155/ERC721
  contracts/adapters/TributeNFT.sol
  test/adapters/tribute-nft.test.js
  test/extensions/erc1155.test.js
  website/docs/contracts/adapters/onboarding/TributeNFT.md
Labels: documentation, enhancement

#376 feat: add/remove extensions + set extension acl flags
  contracts/adapters/Managing.sol
  contracts/adapters/interfaces/IManaging.sol
  test/adapters/managing.test.js
  utils/DeploymentUtil.js
  website/docs/contracts/adapters/configuration/Managing.md
Labels: enhancement

#385 Edit text to clarify what TRUFFLE_MNEMONIC means
  website/docs/tutorial/dao/Configuration.md
Labels: documentation

#387 Clarifications/fixes to tutorial
  website/docs/tutorial/dao/TributeUI.md
Labels: documentation

#388 feat: updated TributeNFT adapter to safely handle erc1155 and erc721 tokens
  contracts/adapters/ERC1155Adapter.sol
  contracts/adapters/TributeNFT.sol
  contracts/extensions/erc1155/ERC1155TokenExtension.sol
  test/adapters/tribute-nft.test.js
  test/extensions/erc1155.test.js
  website/docs/contracts/adapters/onboarding/TributeNFT.md
  website/docs/contracts/extensions/ERC1155.md
Labels: enhancement

#389 More tutorial fixes related to The Graph legacy vs non-legacy
  website/docs/tutorial/dao/Configuration.md
  website/docs/tutorial/dao/TributeUI.md
Labels: documentation

#392 fix: tribute-nft missing require, cleanup code, fix erc1155 ext
  contracts/adapters/TributeNFT.sol
  contracts/extensions/erc1155/ERC1155TokenExtension.sol
Labels: enhancement

#395 chore: added js helper functions
  utils/DeploymentUtil.js
  utils/aclFlags.js
Labels: chore

#397 added dao address on any events coming from an adapter
  contracts/adapters/Distribute.sol
  contracts/adapters/Ragequit.sol
  contracts/adapters/voting/OffchainVoting.sol
  package-lock.json
  package.json
  truffle-config.js
Labels: chore

#399 Update README.md
  README.md
Labels: documentation

#402 docs: enhancements for the dao tutorial
  website/docs/tutorial/dao/Configuration.md
  website/docs/tutorial/dao/Installation.md
  website/docs/tutorial/dao/TributeUI.md
Labels: documentation

#404 weth + mainnet
  contracts/adapters/KycOnboarding.sol
  contracts/helpers/WETH.sol
  contracts/utils/PotentialNewMember.sol
  migrations/2_deploy_contracts.js
  utils/ContractUtil.js
  utils/DeploymentUtil.js
Labels: enhancement

#407 docs: update TributeUI.md
  website/docs/tutorial/dao/TributeUI.md
Labels: documentation

#410 feat: using node url instead of infura key
  README.md
  truffle-config.js
Labels: enhancement

#411 chore: better logs and configs for the deployment script
  migrations/2_deploy_contracts.js
  package-lock.json
  package.json
Labels: chore
