Repository openlawteam/tribute-contracts, pull requests merged in 2021-12, with the labels that each got.

#455 fix: h/m/l issues found with Slither
  .github/workflows/slither.yml
  contracts/adapters/CouponOnboarding.sol
  contracts/adapters/KycOnboarding.sol
  contracts/adapters/Managing.sol
  contracts/adapters/voting/KickBadReporterAdapter.sol
  contracts/extensions/bank/BankFactory.sol
  contracts/extensions/token/erc20/ERC20TokenExtensionFactory.sol
  contracts/helpers/WETH.sol
  package-lock.json
  slither.config.json
Labels: fix

#451 feat: voting rights
  contracts/adapters/KycOnboarding.sol
  contracts/adapters/voting/OffchainVoting.sol
  contracts/adapters/voting/OffchainVotingHash.sol
  contracts/adapters/voting/Voting.sol
  contracts/extensions/token/erc20/ERC20TokenExtension.sol
  contracts/guards/MemberGuard.sol
  contracts/helpers/GovernanceHelper.sol
  contracts/helpers/OffchainVotingHelper.sol
  contracts/test/OLToken.sol
  migrations/2_deploy_contracts.js
  migrations/configs/contracts.config.ts
  package-lock.json
  package.json
  subgraph/mappings/helpers/vote-results.ts
  subgraph/schema.graphql
  test/adapters/configuration.test.js
  test/adapters/offchain.voting.test.js
  test/adapters/voting.test.js
  test/extensions/erc20.test.js
  utils/deployment-util.js
  utils/governance-utils.ts
  utils/offchain-voting-util.js
  utils/oz-util.js
Labels: enhancement

#412 feat: New Adapter - Reimbursement
  .gitignore
  contracts/adapters/BankAdapter.sol
  contracts/adapters/Configuration.sol
  contracts/adapters/CouponOnboarding.sol
  contracts/adapters/Distribute.sol
  contracts/adapters/Financing.sol
  contracts/adapters/GuildKick.sol
  contracts/adapters/KycOnboarding.sol
  contracts/adapters/LendNFT.sol
  contracts/adapters/Managing.sol
  contracts/adapters/Onboarding.sol
  contracts/adapters/Signatures.sol
  contracts/adapters/Tribute.sol
  contracts/adapters/TributeNFT.sol
  contracts/adapters/modifiers/Reimbursable.sol
  contracts/adapters/modifiers/ReimbursableLib.sol
  contracts/adapters/voting/OffchainVoting.sol
  contracts/adapters/voting/Voting.sol
  contracts/companion/GelatoBytes.sol
  contracts/companion/GelatoRelay.sol
  contracts/companion/Gelatofied.sol
  contracts/companion/Reimbursement.sol
  contracts/companion/interfaces/IReimbursement.sol
  contracts/extensions/bank/Bank.sol
  contracts/helpers/DaoHelper.sol
  contracts/utils/Signatures.sol
  migrations/2_deploy_contracts.js
  migrations/configs/contracts.config.ts
  package-lock.json
  package.json
  scripts/verify.ts
  test/adapters/bank.test.js
  test/adapters/financing.test.js
  test/adapters/offchain.voting.test.js
  truffle-config.js
  utils/dao-ids-util.ts
  utils/deployment-util.js
  utils/oz-util.js
Labels: enhancement

#463 docs: warning about the correct branch
  website/docs/tutorial/dao/Configuration.md
  website/docs/tutorial/dao/Deployment.md
  website/docs/tutorial/dao/Installation.md
  website/docs/tutorial/dao/TributeUI.md
Labels: documentation
