Repository openlawteam/tribute-contracts, pull requests merged in 2021-11, with the labels that each got.

#426 fix: deploy utility contracts + check env vars
  .gitignore
  migrations/2_deploy_contracts.js
  migrations/configs/contracts.config.ts
  utils/deployment-util.js
  utils/oz-util.js
Labels: fix

#425 feat: adapter/config addr
  .npmignore
  contracts/adapters/Configuration.sol
  contracts/adapters/interfaces/IConfiguration.sol
  package-lock.json
  package.json
  test/adapters/configuration.test.js
  test/extensions/erc20.test.js
  truffle-config.js
  utils/ContractUtil.js
  utils/TestUtils.js
Labels: enhancement

#430 chore: recover from failed deployment
  deploy-config.js
  migrations/2_deploy_contracts.js
  package.json
  utils/checkpoint-utils.ts
  utils/deployment-util.js
  utils/truffle-util.js
Labels: chore

#432 feat: configuration adapter supports addr conf (#425)
  .npmignore
  contracts/adapters/BankAdapter.sol
  contracts/adapters/Configuration.sol
  contracts/adapters/CouponOnboarding.sol
  contracts/adapters/Distribute.sol
  contracts/adapters/ERC1155Adapter.sol
  contracts/adapters/Financing.sol
  contracts/adapters/GuildKick.sol
  contracts/adapters/LendNFT.sol
  contracts/adapters/Managing.sol
  contracts/adapters/Onboarding.sol
  contracts/adapters/Ragequit.sol
  contracts/adapters/Signatures.sol
  contracts/adapters/Tribute.sol
  contracts/adapters/TributeNFT.sol
  contracts/adapters/interfaces/IConfiguration.sol
  contracts/adapters/interfaces/IManaging.sol
  contracts/adapters/voting/KickBadReporterAdapter.sol
  contracts/adapters/voting/OffchainVoting.sol
  contracts/adapters/voting/OffchainVotingHash.sol
  contracts/adapters/voting/Voting.sol
  contracts/core/DaoRegistry.sol
  contracts/extensions/erc1155/ERC1155TokenExtension.sol
  contracts/extensions/erc1271/ERC1271.sol
  contracts/extensions/executor/Executor.sol
  contracts/extensions/nft/NFT.sol
  contracts/extensions/token/erc20/ERC20TokenExtension.sol
  contracts/extensions/token/erc20/ERC20TransferStrategyWithVesting.sol
  contracts/extensions/token/erc20/IERC20TransferStrategy.sol
  contracts/extensions/token/erc20/InternalTokenVestingExtension.sol
  contracts/extensions/token/erc20/InternalTokenVestingExtensionFactory.sol
  contracts/guards/AdapterGuard.sol
  contracts/helpers/GuildKickHelper.sol
  contracts/test/MockDao.sol
  contracts/test/PixelNFT.sol
  contracts/utils/DaoArtifacts.sol
  contracts/utils/Multicall.sol
  migrations/2_deploy_contracts.js
  package-lock.json
  package.json
  test/adapters/configuration.test.js
  test/adapters/lend-nft.test.js
  test/adapters/offchain.voting.test.js
  test/adapters/tribute-nft.test.js
  test/extensions/erc1155.test.js
  test/extensions/erc20.test.js
  test/extensions/erc721.test.js
  test/extensions/vesting.test.js
  utils/contract-util.js
  utils/oz-util.js
  utils/test-util.js
  website/docs/contracts/adapters/configuration/Configuration.md
  website/docusaurus.config.js
Labels: enhancement

#435 fix: config storage
  contracts/adapters/Configuration.sol
  test/adapters/lend-nft.test.js
  test/extensions/vesting.test.js
  truffle-config.js
Labels: fix

#436 fix: read opt vars from process.env
  migrations/2_deploy_contracts.js
  test/adapters/lend-nft.test.js
Labels: fix

#427 fix: subgraph for latest smart contracts; clean up fixes in deployment files
  migrations/configs/ganache.config.ts
  migrations/configs/goerli.config.ts
  migrations/configs/harmony.config.ts
  migrations/configs/harmonytest.config.ts
  migrations/configs/mainnet.config.ts
  migrations/configs/rinkeby.config.ts
  subgraph/mappings/core/dao-constants.ts
  subgraph/mappings/extensions/bank-extension-mapping.ts
  subgraph/mappings/helpers/proposal-details.ts
  subgraph/mappings/helpers/vote-results.ts
  subgraph/schema.graphql
  utils/deployment-util.js
Labels: fix

#439 chore: read chainId from block
  contracts/adapters/CouponOnboarding.sol
  contracts/adapters/voting/SnapshotProposalContract.sol
  migrations/configs/contracts.config.ts
  utils/deployment-util.js
  website/docs/contracts/adapters/onboarding/CouponOnboarding.md
Labels: chore

#441 docs: update branch version
  website/docs/tutorial/dao/Installation.md
Labels: documentation

#445 chore: bump oz-contracts to v4.3.3
  package-lock.json
  package.json
  subgraph/package-lock.json
  subgraph/package.json
Labels: chore

#442 feat: set DAO configs with Managing proposals
  contracts/adapters/Managing.sol
  contracts/adapters/interfaces/IManaging.sol
  package-lock.json
  package.json
  test/adapters/guildkick.test.js
  test/adapters/managing.test.js
  test/extensions/nft.test.js
  truffle-config.js
  utils/DeploymentUtil.js
Labels: enhancement

#440 fix: receive and save NFTs sent directly to the extensions
  contracts/adapters/NFTAdapter.sol
  contracts/extensions/nft/NFT.sol
  migrations/configs/contracts.config.ts
  test/adapters/lend-nft.test.js
  test/extensions/erc1155.test.js
  test/extensions/erc721.test.js
  utils/test-util.js
Labels: fix

#437 feat: New Adapter - KYC Onboarding
  contracts/adapters/KycOnboarding.sol
  contracts/helpers/DaoHelper.sol
  contracts/helpers/WETH.sol
  migrations/2_deploy_contracts.js
  migrations/configs/contracts.config.ts
  package-lock.json
  scripts/coverage.ts
  test/adapters/kyc-onboarding.test.js
  test/adapters/lend-nft.test.js
  truffle-config.js
  utils/contract-util.js
  utils/dao-ids-util.ts
  utils/deployment-util.js
  utils/offchain-voting-util.js
  utils/oz-util.js
  website/docs/contracts/adapters/onboarding/KycOnboarding.md
  website/docs/contracts/adapters/onboarding/Onboarding.md
  website/sidebars.js
Labels: enhancement

#449 feat: set DAO configs with Managing proposals (#442)
  contracts/adapters/Managing.sol
  contracts/adapters/interfaces/IManaging.sol
  migrations/configs/contracts.config.ts
  package-lock.json
  package.json
  test/adapters/guildkick.test.js
  test/adapters/managing.test.js
  test/adapters/onboarding.test.js
  test/extensions/erc721.test.js
Labels: enhancement

#452 fix: kyc configs and deployment
  migrations/2_deploy_contracts.js
  migrations/configs/contracts.config.ts
  utils/oz-util.js
Labels: fix
