Repository openlawteam/tribute-contracts, pull requests merged in 2022-01, with the labels that each got.

#467 Add polygon deployment
  docker/README-ganache.md
  docker/docker-compose.yml
  migrations/2_deploy_contracts.js
  package.json
  truffle-config.js
  utils/DeploymentUtil.js
Labels: chore

#465 use rinkeby as default for local dev
  docker/README.md
  subgraph/config/subgraph-config.json
Labels: documentation

#466 use rinkeby as default for local dev (web documentation)
  website/docs/tutorial/dao/TributeUI.md
Labels: documentation

#468 fix: several fixes to make it work with tribute-ui
  contracts/adapters/modifiers/ReimbursableLib.sol
  contracts/guards/MemberGuard.sol
  contracts/helpers/OffchainVotingHelper.sol
  migrations/configs/contracts.config.ts
  package.json
  scripts/coverage.ts
  test/adapters/offchain.voting.test.js
Labels: fix

#471 fix: security fixes
  .github/workflows/slither.yml
  contracts/adapters/voting/OffchainVoting.sol
  contracts/core/DaoRegistry.sol
  contracts/extensions/bank/Bank.sol
  contracts/extensions/erc1155/ERC1155TokenExtension.sol
  contracts/extensions/erc1271/ERC1271.sol
  contracts/extensions/executor/Executor.sol
  contracts/extensions/nft/NFT.sol
  contracts/extensions/token/erc20/InternalTokenVestingExtension.sol
  contracts/guards/AdapterGuard.sol
  contracts/helpers/DaoHelper.sol
  contracts/helpers/OffchainVotingHelper.sol
  test/extensions/vesting.test.js
  website/docs/tutorial/extensions/HowToCreateAnExtension.md
Labels: fix

#479 fix: isActiveMember, requestStep, and voting power validation
  contracts/adapters/voting/OffchainVoting.sol
  contracts/core/DaoRegistry.sol
  contracts/guards/MemberGuard.sol
  contracts/helpers/OffchainVotingHelper.sol
  test/adapters/managing.test.js
Labels: fix

#485 fix: impersonation issue
  .gitignore
  contracts/adapters/BankAdapter.sol
  contracts/adapters/CouponOnboarding.sol
  contracts/adapters/Distribute.sol
  contracts/adapters/Financing.sol
  contracts/adapters/GuildKick.sol
  contracts/adapters/KycOnboarding.sol
  contracts/adapters/NFTAdapter.sol
  contracts/adapters/Onboarding.sol
  contracts/adapters/Ragequit.sol
  contracts/adapters/Tribute.sol
  contracts/adapters/TributeNFT.sol
Labels: fix
